name: Extract local authority boundaries
on:
  workflow_dispatch:

jobs:
  download-and-extract:
    runs-on: ubuntu-latest
    steps:
      - name: Download BoundaryLine data
        # Link from https://osdatahub.os.uk/downloads/open/BoundaryLine
        run: |
          curl -Lo BoundaryLine.zip 'https://api.os.uk/downloads/v1/products/BoundaryLine/downloads?area=GB&format=GML&subformat=3&redirect'
          unzip BoundaryLine.zip
          [ -f Data/INSPIRE_AdministrativeUnit.gml ]

      - name: Extract local authorities for England and Wales
        run: |
          sudo apt-get update && sudo apt-get -y install gdal-bin
          # We're in EPSG:27700 so -simplify 10 means to 10m
          ogr2ogr -f GML local-authorities.gml Data/INSPIRE_AdministrativeUnit.gml -simplify 10 -dialect sqlite \
              -sql "select * from AdministrativeUnit where substr(nationalCode, 1, 3) in ('E06', 'E07', 'E08', 'E09', 'W06')"
          zip local-authorities.zip local-authorities.gml

      - name: Get access token
        id: get_token
        run: |
          token=$(
            curl -s https://api.dropbox.com/oauth2/token \
              -d refresh_token=${{ secrets.DROPBOX_REFRESH_TOKEN }} \
              -d grant_type=refresh_token \
              -d client_id=${{ secrets.DROPBOX_APP_KEY }} \
              -d client_secret=${{ secrets.DROPBOX_APP_SECRET }} \
            | jq -Rr 'fromjson | .access_token'
          )
          echo "::add-mask::$token"
          echo "token=$token" >> "$GITHUB_OUTPUT"

      - name: Upload files
        run: |
          f=local-authorities.zip
          echo "Uploading $f"
          curl -s --fail-with-body https://content.dropboxapi.com/2/files/upload \
            -H "Authorization: Bearer ${{ steps.get_token.outputs.token }}" \
            -H "Dropbox-API-Arg: {\"path\":\"/$f\", \"mode\": \"overwrite\"}" \
            -H 'Content-Type: application/octet-stream' \
            --data-binary "@$f"

